face_detection:
  mtcnn:
    threshold: 0.5
    weight_path: ""

face_recognition:
  method: insightface
  insightface:
    threshold: 1.1066
    weight_path: "weights/insightface/model_cpu_final.pth"
  facenet:
    threshold: 161.8
    weight_path: "weights/facenet/data.pt"

